package com.learning.exception;

public class ThrowsDemo {

	void m1() throws Exception {
		int sum = 10/0;
	}
	
	void m2() {
		try {
			m1();
		}catch(Exception e) {
			System.err.println(e.getMessage());
		}
		
	}
	
	public static void main(String[] args) {
		ThrowsDemo obj = new ThrowsDemo();
		
		obj.m2();
	}

}
